### ISSUE TITLE
"besser isses" on leave

### ISSUE THREAD

**Issue by screendriver** [screendriver/jabberbot#15]
If someone leaves the MUC the bot should show a "besser isses" message. This message should appear randomly and not always.

**Comment by rob19780114** [comment]
+1

**Comment by Tr1gg3rH4ppy** [comment]
CR: Display a random "bye" message, like "Pfiat di" and a random greeting on enter.

**Comment by Tr1gg3rH4ppy** [comment]
CR: https://github.com/screendriver/jabberbot/issues/19
